__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/arriba.smk"
include: "rules/fuseq_wes.smk"
include: "rules/fusioncatcher.smk"
include: "rules/gene_fuse.smk"
include: "rules/gene_fuse_report.smk"
include: "rules/star_fusion.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
