---

default_resources:
  mem_mb: 3800
  mem_per_cpu: 3800
  partition: "core"
  threads: 1
  time: "12:00:00"

arriba:
 mem_mb: 30000
 threads: 8

fuseq_wes:
  time: "24:00:00"

fusioncatcher:
  threads: 8
  mem_mb: 30000

gene_fuse:
  threads: 4
  time: "8:00:00"

star:
  threads: 8
  mem_mb: 30000

star_fusion:
  threads: 8
  mem_mb: 30000