$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  required:
    - reference

  star_fusion:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for rule
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to rule

  reference:
    type: object
    description: reference used by callers
    properties:
      star_fusion:
        type: string
        description: star-fusion reference path
