resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "reference/gene_fuse_HES4.hg19.csv"
