resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.3"

arriba:
  assembly: "reference/WASH7P.fna"
  blacklist: "reference/arriba_blacklist.tsv"
  container: "docker://hydragenetics/arriba:2.3.0"
  gtf: "reference/WASH7P.gtf"

arriba_draw_fusion:
  container: "docker://hydragenetics/arriba:2.3.0"
  cytobands: "reference/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv"
  gtf: "reference/WASH7P.gtf"
  protein_domains: "reference/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "reference/gene_fuse_HES4.hg19.csv"
  fasta: "reference/HES45.fna"

fusioncatcher:
  container: "docker://blcdsdockerregistry/fusioncatcher:1.33"
  genome_path: "reference/"

picard_add_read_group:
  container: "docker://hydragenetics/picard:2.25.0"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "reference/"
