name: small integration test

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    # do not run the integration test as this is not set up for this module
    branches:
     # - develop
     # - master
     - dummy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Miniforge3
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true
      - name: Set strict channel
        run: |
          conda config --set channel_priority strict
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install singularity
        run: |
          mamba install -c conda-forge -c bioconda apptainer=1.3.2
      - name: Integration test - small dataset
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile -j 1 --show-failed-logs --configfile config.yaml --use-singularity --singularity-args  " --cleanenv --bind /home/runner "
